# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMT-IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'GoogleMaps'
	pod 'GooglePlaces'
	pod 'SnapKit', '~> 5.0.0'
	pod 'Alamofire', '~> 5.5'

  # Pods for UMT-IOS


end
